# Importing the table named rad

SET GLOBAL local_infile=ON;

use heart_failure;

CREATE TABLE rad (
    ADMID VARCHAR(64),
	PATIENTID VARCHAR(64),
    EXAM_DATE INT,
    EXAM_TIME TIME,
    AGE_GRP_AT_EXAM VARCHAR(10),
    NICIP_CODE VARCHAR(10),
    EXAM_NAME VARCHAR(32)
    );

LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Rad.txt'
INTO TABLE heart_failure.rad
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

# Converting excel date to normal date
UPDATE rad
SET EXAM_DATE = NULL
WHERE EXAM_DATE IS NULL
   OR EXAM_DATE = ''
   OR NOT EXAM_DATE REGEXP '^[0-9]+$';

ALTER TABLE rad
ADD COLUMN EXAM_DATEn DATE;

UPDATE rad
SET EXAM_DATEn = DATE_ADD('1899-12-30', INTERVAL EXAM_DATE DAY)
WHERE EXAM_DATE IS NOT NULL;

select COUNT(*) from rad;
