# Importing the table named itu

SET GLOBAL local_infile=ON;

use heart_failure;

CREATE TABLE ITU (
    ADMID VARCHAR(64),
	PATIENTID VARCHAR(64),
    START_DATE INT,
    START_TIME TIME,
    AGE_GRP_AT_START VARCHAR(10),
    END_DATE INT,
    END_TIME TIME,
    AGE_GRP_AT_END VARCHAR(10)
);

LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/ITU.txt'
INTO TABLE heart_failure.ITU
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

# Converting excel date to normal date
UPDATE ITU
SET START_DATE = NULL
WHERE START_DATE IS NULL
   OR START_DATE = ''
   OR NOT START_DATE REGEXP '^[0-9]+$';

ALTER TABLE ITU
ADD COLUMN sSTART_DATE DATE;

UPDATE ITU
SET sSTART_DATE = DATE_ADD('1899-12-30', INTERVAL START_DATE DAY)
WHERE START_DATE IS NOT NULL;

# Converting excel date to normal date
UPDATE ITU
SET END_DATE = NULL
WHERE END_DATE IS NULL
   OR END_DATE = ''
   OR NOT END_DATE REGEXP '^[0-9]+$';

ALTER TABLE ITU
ADD COLUMN sEND_DATE DATE;

UPDATE ITU
SET sEND_DATE = DATE_ADD('1899-12-30', INTERVAL END_DATE DAY)
WHERE END_DATE IS NOT NULL;

select COUNT(*) from ITU;
