# Importing the table named adm

use heart_failure;

SET GLOBAL local_infile=ON;

CREATE TABLE adm (
	ADMID VARCHAR(64),
    PATIENTID VARCHAR(64),
    ADM_DATE INT,
    ADM_TIME TIME,
    AGE_GRP_AT_ADM VARCHAR(10),
    DIS_DATE INT,
    DIS_TIME TIME,
    AGE_GRP_AT_DIS VARCHAR(10),
    DISCH_DEST INT,
    TFC_CODE INT,
    TFC_DESC VARCHAR(64),
    ADM_SOURCE INT,
    NAT_ADM_METH VARCHAR(5)
);

LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Adm.txt'
INTO TABLE heart_failure.adm
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

# Converting excel date to normal date
UPDATE adm
SET ADM_DATE = NULL
WHERE ADM_DATE IS NULL
   OR ADM_DATE = ''
   OR NOT ADM_DATE REGEXP '^[0-9]+$';

ALTER TABLE adm
ADD COLUMN ADM_DATE_N DATE;

UPDATE adm
SET ADM_DATE_N = DATE_ADD('1899-12-30', INTERVAL ADM_DATE DAY)
WHERE ADM_DATE IS NOT NULL;

# Converting excel date to normal date
UPDATE adm
SET DIS_DATE = NULL
WHERE DIS_DATE IS NULL
   OR DIS_DATE = ''
   OR NOT DIS_DATE REGEXP '^[0-9]+$';

ALTER TABLE adm
ADD COLUMN DIS_DATE_N DATE;

UPDATE adm
SET DIS_DATE_N = DATE_ADD('1899-12-30', INTERVAL DIS_DATE DAY)
WHERE DIS_DATE IS NOT NULL;
