-- IDENTIFY ADMISSION BLOODS WITHIN 3 DAYS OF ADMISSION (PRIOR TO ADMISSION [i.e. IN ED] IF PRESENT) - WHERE SEVERAL ARE PRESENT, THE CLOSEST TO ADMISSION ARE USED;

USE heart_failure;

SELECT
	TABLE_MEGA.ADMID,
    MAX(TABLE_MEGA.WCC) AS WCC,
    MAX(TABLE_MEGA.Hb) AS Hb,
    MAX(TABLE_MEGA.Plts) AS Plts,
    MAX(TABLE_MEGA.Na) AS Na,
    MAX(TABLE_MEGA.K) AS K,
    MAX(TABLE_MEGA.Cr) AS Cr,
    MAX(TABLE_MEGA.Ur) AS Ur,
    MAX(TABLE_MEGA.CRP) AS CRP,
    MAX(TABLE_MEGA.Alb) AS Alb,
    MAX(TABLE_MEGA.INR) AS INR,
    MAX(TABLE_MEGA.Glucose) AS Glucose,
    MAX(TABLE_MEGA.Troponin) AS Troponin,
    MAX(TABLE_MEGA.Lactate) AS Lactate
FROM
	(SELECT
		NUMBERED_LABS.ADMID,
		NUMBERED_LABS.DIFF_TIME,
		NUMBERED_LABS.TEST,
		NUMBERED_LABS.ORD_VALUE,
		CASE WHEN NUMBERED_LABS.TEST LIKE '%white cell%' THEN NUMBERED_LABS.ORD_VALUE END WCC,
		CASE WHEN NUMBERED_LABS.TEST LIKE 'haemoglobin%' THEN NUMBERED_LABS.ORD_VALUE END Hb,
		CASE WHEN NUMBERED_LABS.TEST LIKE '%platelets%' THEN NUMBERED_LABS.ORD_VALUE END Plts,
		CASE WHEN NUMBERED_LABS.TEST LIKE 'sodium%' THEN NUMBERED_LABS.ORD_VALUE END Na,
		CASE WHEN NUMBERED_LABS.TEST LIKE 'potassium%' THEN NUMBERED_LABS.ORD_VALUE END K,
		CASE WHEN NUMBERED_LABS.TEST LIKE '%creatinine%' THEN NUMBERED_LABS.ORD_VALUE END Cr,
		CASE WHEN NUMBERED_LABS.TEST LIKE '%urea%' THEN NUMBERED_LABS.ORD_VALUE END Ur,
		CASE WHEN NUMBERED_LABS.TEST LIKE '%CRP%' THEN NUMBERED_LABS.ORD_VALUE END CRP,
		CASE WHEN NUMBERED_LABS.TEST LIKE '%albumin%' THEN NUMBERED_LABS.ORD_VALUE END Alb,
		CASE WHEN NUMBERED_LABS.TEST LIKE '%INR%' THEN NUMBERED_LABS.ORD_VALUE END INR,
		CASE WHEN NUMBERED_LABS.TEST LIKE '%glucose%' THEN NUMBERED_LABS.ORD_VALUE END Glucose,
		CASE WHEN NUMBERED_LABS.TEST LIKE '%troponin%' THEN NUMBERED_LABS.ORD_VALUE END Troponin,
        CASE WHEN NUMBERED_LABS.TEST LIKE '%lactate%' THEN NUMBERED_LABS.ORD_VALUE END Lactate
	FROM (
		SELECT
			probs.ADMID,
			CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME) AS ADMISSION_DATETIME,
			CONCAT(labs.RES_DATE_N, ' ', labs.RES_TIME) AS RESULT_DATETIME,
			labs.TEST,
			labs.ORD_VALUE,
			TIMESTAMPDIFF(SECOND, CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME), CONCAT(labs.RES_DATE_N, ' ', labs.RES_TIME)) AS DIFF_TIME,
			ROW_NUMBER() OVER (PARTITION BY probs.ADMID, labs.TEST ORDER BY (TIMESTAMPDIFF(SECOND, CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME), CONCAT(labs.RES_DATE_N, ' ', labs.RES_TIME))) ASC) AS NUMBERED_ROW
		FROM
			probs
			LEFT JOIN adm ON probs.ADMID = adm.ADMID
			LEFT JOIN labs ON probs.ADMID = labs.ADMID
		WHERE
			(probs.PROB_NAME LIKE '%HFpEF%'
			OR probs.PROB_NAME LIKE '%preserved%'
			OR probs.PROB_NAME LIKE '%diastolic%'
			OR probs.PROB_NAME LIKE '%normal ejection%'
			OR probs.PROB_NAME LIKE '%DHF%')    
			AND ((labs.TEST LIKE '%white cell%' 
				OR labs.TEST LIKE 'haemoglobin%' 
				OR labs.TEST LIKE '%platelets%' 
				OR labs.TEST LIKE 'sodium%' 
				OR labs.TEST LIKE 'potassium%' 
				OR labs.TEST LIKE '%creatinine%' 
				OR labs.TEST LIKE '%urea%' 
				OR labs.TEST LIKE '%CRP%' 
				OR labs.TEST LIKE '%albumin%' 
				OR labs.TEST LIKE '%INR%' 
				OR labs.TEST LIKE '%glucose%' 
				OR labs.TEST LIKE '%troponin%'
                OR labs.TEST LIKE '%lactate%')
				AND CONCAT(labs.RES_DATE_N, ' ', labs.RES_TIME) < DATE_ADD((CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME)), INTERVAL 3 DAY))) AS NUMBERED_LABS
		WHERE NUMBERED_LABS.NUMBERED_ROW = 1) AS TABLE_MEGA
GROUP BY
	TABLE_MEGA.ADMID;
