-- IDENTIFY THE CLOSEST BNP TO ADMISSION WITHIN 3 DAYS OF ADMISSION OR 1 YEAR PREVIOUS, IF MULTIPLE, CLOSEST IS CHOSEN;

SELECT
	ORDERED_BNPS.ADMID,
    ORDERED_BNPS.PATIENTID,
    ORDERED_BNPS.ADMISSION_DATETIME,
    ORDERED_BNPS.RESULT_DATETIME,
    ORDERED_BNPS.TEST,
    ORDERED_BNPS.ORD_VALUE,
    ORDERED_BNPS.DIFF_TIME,
    CASE WHEN ORDERED_BNPS.TEST LIKE '%peptide%' THEN ORDERED_BNPS.ORD_VALUE END BNP
FROM (
	SELECT
		probs.ADMID,
        probs.PATIENTID,
		CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME) AS ADMISSION_DATETIME,
		CONCAT(labs.RES_DATE_N, ' ', labs.RES_TIME) AS RESULT_DATETIME,
		labs.TEST,
		labs.ORD_VALUE,
		ABS(TIMESTAMPDIFF(SECOND, CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME), CONCAT(labs.RES_DATE_N, ' ', labs.RES_TIME))) AS DIFF_TIME,
        ROW_NUMBER() OVER (PARTITION BY probs.ADMID ORDER BY (ABS(TIMESTAMPDIFF(SECOND, CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME), CONCAT(labs.RES_DATE_N, ' ', labs.RES_TIME)))) ASC) AS NUMBERED_ROW
	FROM
		probs
		LEFT JOIN adm ON probs.ADMID = adm.ADMID
		LEFT JOIN labs ON probs.PATIENTID = labs.PATIENTID
	WHERE
		(probs.PROB_NAME LIKE '%HFpEF%'
		OR probs.PROB_NAME LIKE '%preserved%'
		OR probs.PROB_NAME LIKE '%diastolic%'
		OR probs.PROB_NAME LIKE '%normal ejection%'
		OR probs.PROB_NAME LIKE '%DHF%')
		AND labs.TEST LIKE '%peptide%'
		AND ((CONCAT(labs.RES_DATE_N, ' ', labs.RES_TIME) < DATE_ADD((CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME)), INTERVAL 3 DAY)) 
		OR (CONCAT(labs.RES_DATE_N, ' ', labs.RES_TIME) < DATE_ADD((CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME)), INTERVAL -1 YEAR)))) AS ORDERED_BNPS
	WHERE
		ORDERED_BNPS.NUMBERED_ROW = 1;
