use heart_failure;

CREATE TABLE probs (
	ADMID VARCHAR(64),
    PATIENTID VARCHAR(64),
    NOTED_DATE INT,
    AGE_GRP_AT_NOTED_DATE VARCHAR(10),
    RESOLVED_DATE INT,
    AGE_GRP_AT_RESOLVED_DATE VARCHAR(10),
    PROBLEM VARCHAR(100),
    PROB_NAME VARCHAR(100)
);

LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Probs.txt'
INTO TABLE heart_failure.probs
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

# Converting excel date to normal date
UPDATE probs
SET NOTED_DATE = NULL
WHERE NOTED_DATE IS NULL
   OR NOTED_DATE = ''
   OR NOT NOTED_DATE REGEXP '^[0-9]+$';

ALTER TABLE probs
ADD COLUMN NOTED_DATEn DATE;

UPDATE probs
SET NOTED_DATEn = DATE_ADD('1899-12-30', INTERVAL NOTED_DATE DAY)
WHERE NOTED_DATE IS NOT NULL;

# Converting excel date to normal date
UPDATE probs
SET RESOLVED_DATE = NULL
WHERE RESOLVED_DATE IS NULL
   OR RESOLVED_DATE = ''
   OR NOT RESOLVED_DATE REGEXP '^[0-9]+$';

ALTER TABLE probs
ADD COLUMN RESOLVED_DATEn DATE;

UPDATE probs
SET RESOLVED_DATEn = DATE_ADD('1899-12-30', INTERVAL RESOLVED_DATE DAY)
WHERE RESOLVED_DATE IS NOT NULL;

select COUNT(*) from fluid;

select * from probs
where ADMID = "BA70F8ED023C2245F367C298EDF7F2930BD732C5F48895A69005DF64D6357A34";
# , in the problem name leads to contraction of the problem
