-- IDENTIFY ADMISSION OBSERVATIONS WITHIN 24 HOURS OF ADMISSION (PRIOR TO ADMISSION [i.e. IN ED] IF PRESENT) - WHERE SEVERAL ARE PRESENT, THE CLOSEST TO ADMISSION ARE USED;

SELECT
	OBSERVATIONS_MEGA_TABLE.ADMID,
    MAX(OBSERVATIONS_MEGA_TABLE.O2SAT) AS O2SAT,
    MAX(OBSERVATIONS_MEGA_TABLE.RR) AS RR,
    MAX(OBSERVATIONS_MEGA_TABLE.SBP) AS SBP,
    MAX(OBSERVATIONS_MEGA_TABLE.DBP) AS DBP,
    MAX(OBSERVATIONS_MEGA_TABLE.HR) AS HR,
    MAX(OBSERVATIONS_MEGA_TABLE.Weight) AS Weight,
    MAX(OBSERVATIONS_MEGA_TABLE.Height) AS Height
FROM (
	SELECT
		NUMBERED_OBSERVATIONS.ADMID,
		NUMBERED_OBSERVATIONS.DIFF_TIME,
		CASE WHEN NUMBERED_OBSERVATIONS.OBS_TYPE LIKE '%O2SAT%' THEN NUMBERED_OBSERVATIONS.REC END O2SAT,
		CASE WHEN NUMBERED_OBSERVATIONS.OBS_TYPE LIKE '%RR%' THEN NUMBERED_OBSERVATIONS.REC END RR,
		CASE WHEN NUMBERED_OBSERVATIONS.OBS_TYPE LIKE '%SBP%' THEN NUMBERED_OBSERVATIONS.REC END SBP,
		CASE WHEN NUMBERED_OBSERVATIONS.OBS_TYPE LIKE '%DBP%' THEN NUMBERED_OBSERVATIONS.REC END DBP,
		CASE WHEN NUMBERED_OBSERVATIONS.OBS_TYPE LIKE '%HR%' THEN NUMBERED_OBSERVATIONS.REC END HR,
		CASE WHEN NUMBERED_OBSERVATIONS.OBS_TYPE LIKE '%WEIGHT%' THEN NUMBERED_OBSERVATIONS.REC END Weight,
		CASE WHEN NUMBERED_OBSERVATIONS.OBS_TYPE LIKE '%HEIGHT%' THEN NUMBERED_OBSERVATIONS.REC END Height
	FROM
		(SELECT 
			probs.ADMID,
			CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME) AS ADMISSION_DATETIME,
			CONCAT(obs.REC_DATE_N, ' ', obs.REC_TIME) AS REC_DATETIME,
			obs.OBS_TYPE,
			obs.REC,
			TIMESTAMPDIFF(SECOND, (CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME)), (CONCAT(obs.REC_DATE_N, ' ', obs.REC_TIME))) AS DIFF_TIME,
			ROW_NUMBER() OVER (PARTITION BY probs.ADMID, OBS_TYPE ORDER BY (TIMESTAMPDIFF(SECOND, (CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME)), (CONCAT(obs.REC_DATE_N, ' ', obs.REC_TIME)))) ASC) AS NUMBERED_ROW
		FROM 
			probs
			LEFT JOIN adm ON probs.ADMID = adm.ADMID
			LEFT JOIN obs on probs.ADMID = obs.ADMID
		WHERE
			(probs.PROB_NAME LIKE '%HFpEF%'
			OR probs.PROB_NAME LIKE '%preserved%'
			OR probs.PROB_NAME LIKE '%diastolic%'
			OR probs.PROB_NAME LIKE '%normal ejection%'
			OR probs.PROB_NAME LIKE '%DHF%')
			AND CONCAT(obs.REC_DATE_N, ' ', obs.REC_TIME) < DATE_ADD((CONCAT(adm.ADM_DATE, ' ', adm.ADM_TIME)), INTERVAL 24 HOUR)
		) AS NUMBERED_OBSERVATIONS
	WHERE NUMBERED_OBSERVATIONS.NUMBERED_ROW = 1) AS OBSERVATIONS_MEGA_TABLE
GROUP BY
	OBSERVATIONS_MEGA_TABLE.ADMID