SET GLOBAL local_infile=ON;

use heart_failure;

CREATE TABLE labs (
    ADMID VARCHAR(100),
	PATIENTID VARCHAR(64),
    RES_DATE INT,
    RES_TIME TIME,
    AGE_GRP_AT_RES VARCHAR(10),
    TEST VARCHAR(64),
    ORD_VALUE VARCHAR(150),
    REFERENCE_UNIT VARCHAR(64)
    );
    
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Labs.txt' 
INTO TABLE heart_failure.labs 
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

# Converting excel date to normal date
ALTER TABLE labs
ADD COLUMN RES_DATE_N DATE;

UPDATE labs
SET RES_DATE = NULL
WHERE RES_DATE IS NULL
   OR RES_DATE = ''
   OR NOT RES_DATE REGEXP '^[0-9]+$';

UPDATE labs
SET RES_DATE_N = DATE_ADD('1899-12-30', INTERVAL RES_DATE DAY)
WHERE RES_DATE IS NOT NULL;