use heart_failure;

CREATE TABLE algy (
    ADMID VARCHAR(64),
    PATIENTID VARCHAR(64),
    ALGY_DATE INT,
    AGE_GRP_AT_ALGY VARCHAR(10),
    ALLERGEN_TYPE VARCHAR(110),
    ALLERGEN VARCHAR(110),
    REACTION VARCHAR(64)
);

LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Algy.txt'
INTO TABLE heart_failure.algy
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

# Converting excel date to normal date
UPDATE algy
SET ALGY_DATE = NULL
WHERE ALGY_DATE IS NULL
   OR ALGY_DATE = ''
   OR NOT ALGY_DATE REGEXP '^[0-9]+$';

ALTER TABLE algy
ADD COLUMN ALGY_DATE_N DATE;

UPDATE algy
SET ALGY_DATE_N = DATE_ADD('1899-12-30', INTERVAL ALGY_DATE DAY)
WHERE ALGY_DATE IS NOT NULL;