SET GLOBAL local_infile=ON;

use heart_failure;

CREATE TABLE meds (
    ADMID VARCHAR(64),
	PATIENTID VARCHAR(64),
    MEDICATION VARCHAR(64),
    MED_ROUTE VARCHAR(32),
    SCHED_START_DATE INT,
    SCHED_START_TIME TIME,
    AGE_GRP_AT_SCHED_START VARCHAR(10),
    SCHED_END_DATE INT,
    SCHED_END_TIME TIME,
    AGE_GRP_AT_SCHED_END VARCHAR(10),
    DISCON_DATE INT,
    DISCON_TIME TIME,
    AGE_GRP_AT_DISCONTINUE VARCHAR(10),
    FREQUENCY VARCHAR(32),
    DOSE VARCHAR(10),
    DOSE_UNIT VARCHAR(16)
    );

LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Meds.txt'
INTO TABLE heart_failure.meds
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

# Converting excel date to normal date
UPDATE meds
SET SCHED_START_DATE = NULL
WHERE SCHED_START_DATE IS NULL
   OR SCHED_START_DATE = ''
   OR NOT SCHED_START_DATE REGEXP '^[0-9]+$';

ALTER TABLE meds
ADD COLUMN SCHED_START_DATE_N DATE;

UPDATE meds
SET SCHED_START_DATE_N = DATE_ADD('1899-12-30', INTERVAL SCHED_START_DATE DAY)
WHERE SCHED_START_DATE IS NOT NULL;

# Converting excel date to normal date
UPDATE meds
SET SCHED_END_DATE = NULL
WHERE SCHED_END_DATE IS NULL
   OR SCHED_END_DATE = ''
   OR NOT SCHED_END_DATE REGEXP '^[0-9]+$';

ALTER TABLE meds
ADD COLUMN SCHED_END_DATE_N DATE;

UPDATE meds
SET SCHED_END_DATE_N = DATE_ADD('1899-12-30', INTERVAL SCHED_END_DATE DAY)
WHERE SCHED_END_DATE IS NOT NULL;

# Converting excel date to normal date
UPDATE meds
SET DISCON_DATE = NULL
WHERE DISCON_DATE IS NULL
   OR DISCON_DATE = ''
   OR NOT DISCON_DATE REGEXP '^[0-9]+$';

ALTER TABLE meds
ADD COLUMN DISCON_DATE_N DATE;

UPDATE meds
SET DISCON_DATE_N = DATE_ADD('1899-12-30', INTERVAL DISCON_DATE DAY)
WHERE DISCON_DATE IS NOT NULL;