-- IDENTIFY DISTINCT ITU ADMISSION - ONLY ONE PER PATIENT (ONE WITH DISCHDATE THE SAME AS ADMDATE SO COMBINED AS ONE ADMISSION);

USE heart_failure;

SELECT
	ITU_ADMISSIONS.ADMID,
    MIN(ITU_ADMISSIONS.ITU_ADMDATETIME) AS ITU_ADMDATETIME,
    MAX(ITU_ADMISSIONS.ITU_DISCHDATETIME) AS ITU_DISCHDATETIME,
    SUM(ITU_ADMISSIONS.DURATION_OF_ITU) AS DURATION_OF_ITU
FROM (
	SELECT DISTINCT
		probs.ADMID,
		CONCAT(itu.START_DATE, ' ', itu.START_TIME) AS ITU_ADMDATETIME,
		CONCAT(itu.END_DATE, ' ', itu.END_TIME) AS ITU_DISCHDATETIME,
		TIMESTAMPDIFF(SECOND, CONCAT(itu.START_DATE, ' ', itu.START_TIME), CONCAT(itu.END_DATE, ' ', itu.END_TIME)) AS DURATION_OF_ITU
	FROM
		probs
		LEFT JOIN itu ON probs.ADMID = itu.ADMID
	WHERE
		(probs.PROB_NAME LIKE '%HFpEF%'
		OR probs.PROB_NAME LIKE '%preserved%'
		OR probs.PROB_NAME LIKE '%diastolic%'
		OR probs.PROB_NAME LIKE '%normal ejection%'
		OR probs.PROB_NAME LIKE '%DHF%')
	) AS ITU_ADMISSIONS
GROUP BY
	ITU_ADMISSIONS.ADMID;